"""Unit tests for app/core/config.py — Settings and LLMSemaphoreLimits."""
import os
from unittest.mock import patch

import pytest
from pydantic import ValidationError

from app.core.config import LLMSemaphoreLimits, Settings


class TestLLMSemaphoreLimits:
    def test_default_interactive(self):
        assert LLMSemaphoreLimits().interactive == 5

    def test_default_background(self):
        assert LLMSemaphoreLimits().background == 2

    def test_default_audit(self):
        assert LLMSemaphoreLimits().audit == 1

    def test_custom_values(self):
        lim = LLMSemaphoreLimits(interactive=10, background=4, audit=2)
        assert lim.interactive == 10
        assert lim.background == 4
        assert lim.audit == 2

    def test_non_integer_raises(self):
        with pytest.raises(ValidationError):
            LLMSemaphoreLimits(interactive="not-a-number")


class TestSettingsDefaults:
    def test_app_name_default(self):
        assert Settings().app_name == "doc-agent"

    def test_debug_default_is_false(self):
        assert Settings().debug is False

    def test_postgres_url_default_scheme(self):
        assert Settings().postgres_url.startswith("postgresql+asyncpg://")

    def test_redis_url_default_scheme(self):
        assert Settings().redis_url.startswith("redis://")

    def test_milvus_host_default(self):
        assert Settings().milvus_host == "localhost"

    def test_milvus_port_default(self):
        assert Settings().milvus_port == 19530

    def test_milvus_alias_default(self):
        assert Settings().milvus_alias == "default"

    def test_knowledge_base_version_default(self):
        assert Settings().knowledge_base_version == "v1"

    def test_mq_stream_name_default(self):
        assert Settings().mq_stream_name == "doc-agent:tasks"

    def test_mq_consumer_group_default(self):
        assert Settings().mq_consumer_group == "doc-agent-workers"

    def test_llm_semaphore_limits_default(self):
        s = Settings()
        assert isinstance(s.llm_semaphore_limits, LLMSemaphoreLimits)
        assert s.llm_semaphore_limits.interactive == 5
        assert s.llm_semaphore_limits.background == 2
        assert s.llm_semaphore_limits.audit == 1


class TestSettingsFromEnv:
    def test_app_name_overridden_by_env(self):
        with patch.dict(os.environ, {"APP_NAME": "my-service"}):
            assert Settings().app_name == "my-service"

    def test_debug_overridden_by_env(self):
        with patch.dict(os.environ, {"DEBUG": "true"}):
            assert Settings().debug is True

    def test_postgres_url_overridden_by_env(self):
        url = "postgresql+asyncpg://root:secret@db:5432/prod"
        with patch.dict(os.environ, {"POSTGRES_URL": url}):
            assert Settings().postgres_url == url

    def test_redis_url_overridden_by_env(self):
        url = "redis://:pass@redis-host:6380/1"
        with patch.dict(os.environ, {"REDIS_URL": url}):
            assert Settings().redis_url == url

    def test_milvus_port_overridden_by_env(self):
        with patch.dict(os.environ, {"MILVUS_PORT": "19531"}):
            assert Settings().milvus_port == 19531

    def test_knowledge_base_version_overridden_by_env(self):
        with patch.dict(os.environ, {"KNOWLEDGE_BASE_VERSION": "v2"}):
            assert Settings().knowledge_base_version == "v2"

    def test_llm_semaphore_limits_nested_delimiter(self):
        with patch.dict(os.environ, {"LLM_SEMAPHORE_LIMITS__INTERACTIVE": "20"}):
            assert Settings().llm_semaphore_limits.interactive == 20

    def test_mq_consumer_name_overridden_by_env(self):
        with patch.dict(os.environ, {"MQ_CONSUMER_NAME": "worker-1"}):
            assert Settings().mq_consumer_name == "worker-1"


class TestMQConsumerNameAutoGenerated:
    def test_consumer_name_contains_hostname(self):
        import socket
        os.environ.pop("MQ_CONSUMER_NAME", None)
        assert socket.gethostname() in Settings().mq_consumer_name

    def test_consumer_name_contains_pid(self):
        os.environ.pop("MQ_CONSUMER_NAME", None)
        assert str(os.getpid()) in Settings().mq_consumer_name
