"""Unit tests for app/config.py — Settings and LLMSemaphoreLimits."""
import os
from unittest.mock import patch

import pytest
from pydantic import ValidationError

from app.config import LLMSemaphoreLimits, Settings


class TestLLMSemaphoreLimits:
    def test_default_interactive(self):
        assert LLMSemaphoreLimits().interactive == 5

    def test_default_background(self):
        assert LLMSemaphoreLimits().background == 2

    def test_default_audit(self):
        assert LLMSemaphoreLimits().audit == 1

    def test_custom_values(self):
        lim = LLMSemaphoreLimits(interactive=10, background=4, audit=2)
        assert lim.interactive == 10
        assert lim.background == 4
        assert lim.audit == 2

    def test_non_integer_raises(self):
        with pytest.raises(ValidationError):
            LLMSemaphoreLimits(interactive="not-a-number")


class TestSettingsDefaults:
    def test_app_name_default(self):
        s = Settings()
        assert s.app_name == "doc-agent"

    def test_debug_default_is_false(self):
        s = Settings()
        assert s.debug is False

    def test_mysql_url_default_scheme(self):
        s = Settings()
        assert s.mysql_url.startswith("mysql+aiomysql://")

    def test_redis_url_default_scheme(self):
        s = Settings()
        assert s.redis_url.startswith("redis://")

    def test_milvus_host_default(self):
        s = Settings()
        assert s.milvus_host == "localhost"

    def test_milvus_port_default(self):
        s = Settings()
        assert s.milvus_port == 19530

    def test_milvus_alias_default(self):
        s = Settings()
        assert s.milvus_alias == "default"

    def test_knowledge_base_version_default(self):
        s = Settings()
        assert s.knowledge_base_version == "v1"

    def test_mq_stream_name_default(self):
        s = Settings()
        assert s.mq_stream_name == "doc-agent:tasks"

    def test_mq_consumer_group_default(self):
        s = Settings()
        assert s.mq_consumer_group == "doc-agent-workers"

    def test_llm_semaphore_limits_default(self):
        s = Settings()
        assert isinstance(s.llm_semaphore_limits, LLMSemaphoreLimits)
        assert s.llm_semaphore_limits.interactive == 5
        assert s.llm_semaphore_limits.background == 2
        assert s.llm_semaphore_limits.audit == 1


class TestSettingsFromEnv:
    def test_app_name_overridden_by_env(self):
        with patch.dict(os.environ, {"APP_NAME": "my-service"}):
            s = Settings()
        assert s.app_name == "my-service"

    def test_debug_overridden_by_env(self):
        with patch.dict(os.environ, {"DEBUG": "true"}):
            s = Settings()
        assert s.debug is True

    def test_mysql_url_overridden_by_env(self):
        url = "mysql+aiomysql://root:secret@db:3306/prod"
        with patch.dict(os.environ, {"MYSQL_URL": url}):
            s = Settings()
        assert s.mysql_url == url

    def test_redis_url_overridden_by_env(self):
        url = "redis://:pass@redis-host:6380/1"
        with patch.dict(os.environ, {"REDIS_URL": url}):
            s = Settings()
        assert s.redis_url == url

    def test_milvus_port_overridden_by_env(self):
        with patch.dict(os.environ, {"MILVUS_PORT": "19531"}):
            s = Settings()
        assert s.milvus_port == 19531

    def test_knowledge_base_version_overridden_by_env(self):
        with patch.dict(os.environ, {"KNOWLEDGE_BASE_VERSION": "v2"}):
            s = Settings()
        assert s.knowledge_base_version == "v2"

    def test_llm_semaphore_limits_nested_delimiter(self):
        with patch.dict(os.environ, {"LLM_SEMAPHORE_LIMITS__INTERACTIVE": "20"}):
            s = Settings()
        assert s.llm_semaphore_limits.interactive == 20

    def test_mq_consumer_name_overridden_by_env(self):
        with patch.dict(os.environ, {"MQ_CONSUMER_NAME": "worker-1"}):
            s = Settings()
        assert s.mq_consumer_name == "worker-1"


class TestMQConsumerNameAutoGenerated:
    def test_consumer_name_contains_hostname(self):
        import socket
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("MQ_CONSUMER_NAME", None)
            s = Settings()
        assert socket.gethostname() in s.mq_consumer_name

    def test_consumer_name_contains_pid(self):
        import os as _os
        _os.environ.pop("MQ_CONSUMER_NAME", None)
        s = Settings()
        assert str(_os.getpid()) in s.mq_consumer_name
